=== maplestory-music/maplebgm-db/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MapleStory music database",
  "description": "Definitive MapleStory music database",
  "type": "array",
  "items": {
    "title": "MapleStory music",
    "type": "object",
    "properties": {
      "decoration": {
        "type": "object",
        "properties": {
          "minorTrack": {
            "description": "Track is a segment of another song",
            "type": "boolean"
          }
        }
      },
      "description": {
        "description": "Description of the song's usage",
        "type": "string"
      },
      "filename": {
        "type": "string"
      },
      "mark": {
        "description": "Map icon associated with the song",
        "type": "string"
      },
      "metadata": {
        "type": "object",
        "properties": {
          "albumArtist": {
            "type": "string"
          },
          "artist": {
            "type": "string"
          },
          "subtitle": {
            "description": "Song title from data",
            "type": "string"
          },
          "title": {
            "description": "Official song title",
            "type": "string"
          },
          "year": {
            "type": "string"
          }
        },
        "required": ["albumArtist", "artist", "title", "year"]
      },
      "source": {
        "type": "object",
        "properties": {
          "client": {
            "description": "Client of origin",
            "type": "string"
          },
          "date": {
            "description": "Date of release",
            "type": "string"
          },
          "structure": {
            "description": "Folder structure",
            "type": "string"
          },
          "version": {
            "description": "Version of origin",
            "type": "string"
          }
        },
        "required": ["structure"]
      },
      "youtube": {
        "description": "YouTube video identifier",
        "type": "string"
      }
    },
    "required": [
      "description",
      "filename",
      "mark",
      "metadata",
      "source",
      "youtube"
    ]
  }
}

=== maplestory-music/maplebgm-db/bgm/BgmWz2Chair.json
[
  {
    "decoration": {
      "minorTrack": true
    },
    "description": "Mu Lung Night Troupe chair effect",
    "filename": "BaekChoBoatParty_Chair",
    "mark": "3019355",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Herb Town Boat Party -Chair-",
      "year": "2024"
    },
    "source": {
      "client": "CMS",
      "date": "2024-10-16",
      "structure": "BgmWz2Chair",
      "version": "2.11"
    },
    "youtube": "wBwQf5NZ2zo"
  },
  {
    "description": "Superstar Pink Bean chair effect",
    "filename": "SuperstarPinkBeanChairBGM",
    "mark": "3018286",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Superstar Pink Bean Chair",
      "year": "2019"
    },
    "source": {
      "client": "CMST",
      "date": "2019-02-01",
      "structure": "BgmWz2Chair",
      "version": "1.48"
    },
    "youtube": "7FSIE0hPxos"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm32.json
[
  {
    "description": "Stone Colossus Innards",
    "filename": "TheColossalHeart",
    "mark": "Colossus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The Colossal Heart",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-04-18",
      "structure": "Bgm32",
      "version": "1.2.476"
    },
    "youtube": "hX73YhOINKA"
  },
  {
    "description": "Stone Colossus Body",
    "filename": "TheLivingMountain",
    "mark": "Colossus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The Living Mountain",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-04-18",
      "structure": "Bgm32",
      "version": "1.2.476"
    },
    "youtube": "sW2zoOX8iUc"
  },
  {
    "description": "Stone Colossus",
    "filename": "TheRaiders",
    "mark": "Colossus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The Raiders",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-04-18",
      "structure": "Bgm32",
      "version": "1.2.476"
    },
    "youtube": "mVR37_LjJUk"
  },
  {
    "description": "Survival event minigame",
    "filename": "TheRush",
    "mark": "MinigameStation",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The Rush",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-04-18",
      "structure": "Bgm32",
      "version": "1.2.476"
    },
    "youtube": "8DzLlqjEnxc"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm44.json
[
  {
    "description": "Ursus boss theme (Phase 4)",
    "filename": "Desperately",
    "mark": "Urus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Desperately",
      "year": "2015"
    },
    "source": {
      "client": "KMST",
      "date": "2015-08-12",
      "structure": "Bgm44",
      "version": "1.2.018"
    },
    "youtube": "vZybFbSlUgc"
  },
  {
    "description": "Ursus entrance map",
    "filename": "SheSellsALuckyThing",
    "mark": "Urus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "She Sells a Lucky Thing",
      "year": "2015"
    },
    "source": {
      "client": "KMST",
      "date": "2015-08-12",
      "structure": "Bgm44",
      "version": "1.2.018"
    },
    "youtube": "60pIpRzbMBg"
  },
  {
    "description": "Ursus boss theme (Phase 1)",
    "filename": "TheKingOfDestruction",
    "mark": "Urus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The King of Destruction",
      "year": "2015"
    },
    "source": {
      "client": "KMS",
      "date": "2015-08-20",
      "structure": "Bgm44",
      "version": "1.2.243"
    },
    "youtube": "krltH4ZKh04"
  },
  {
    "decoration": {
      "minorTrack": true
    },
    "description": "Ursus boss theme (Phase 1)",
    "filename": "TheKingOfDestruction (Original Version)",
    "mark": "Urus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The King of Destruction (Original Version)",
      "year": "2015"
    },
    "source": {
      "client": "KMST",
      "date": "2015-08-12",
      "structure": "Bgm44",
      "version": "1.2.018"
    },
    "youtube": "23CSJNc0Vd8"
  },
  {
    "description": "Ursus boss theme (Phase 2)",
    "filename": "TheSilentWar",
    "mark": "Urus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The Silent War",
      "year": "2015"
    },
    "source": {
      "client": "KMST",
      "date": "2015-08-12",
      "structure": "Bgm44",
      "version": "1.2.018"
    },
    "youtube": "AC6D15z_1pU"
  },
  {
    "description": "Ursus boss theme (Phase 3)",
    "filename": "WildFury",
    "mark": "Urus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Wild Fury",
      "year": "2015"
    },
    "source": {
      "client": "KMS",
      "date": "2015-08-20",
      "structure": "Bgm44",
      "version": "1.2.243"
    },
    "youtube": "mx-yZp8nC9A"
  },
  {
    "description": "Ursus boss theme (Phase 3)",
    "filename": "WildFury (Original Version)",
    "mark": "Urus",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Wild Fury (Original Version)",
      "year": "2015"
    },
    "source": {
      "client": "KMST",
      "date": "2015-08-12",
      "structure": "Bgm44",
      "version": "1.2.018"
    },
    "youtube": "f9gy70JX_8c"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm17.json
[
  {
    "description": "Evolution System",
    "filename": "EvolvingWorld",
    "mark": "EvolvingSystem",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Evolving World",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-09-13",
      "structure": "Bgm17",
      "version": "1.2.450"
    },
    "youtube": "0WLtsCqEQ4Q"
  },
  {
    "description": "Gold Beach",
    "filename": "GoldBeach",
    "mark": "Goldrich",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Gold Beach",
      "year": "2012"
    },
    "source": {
      "client": "KMS",
      "date": "2012-11-15",
      "structure": "Bgm17",
      "version": "1.2.178"
    },
    "youtube": "pyxpWEl3St0"
  },
  {
    "description": "Mu Lung Dojo First Tier, Foggy Forest Training Center",
    "filename": "MureungSchool1",
    "mark": "ForestTraining",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Mu Lung Raid 1",
      "year": "2008"
    },
    "source": {
      "client": "KMST",
      "date": "2008-09-18",
      "structure": "Bgm17",
      "version": "1.2.163"
    },
    "youtube": "bqR0o6TkkQk"
  },
  {
    "description": "Mu Lung Dojo Second Tier",
    "filename": "MureungSchool2",
    "mark": "MuruengRaid",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Mu Lung Raid 2",
      "year": "2008"
    },
    "source": {
      "client": "KMST",
      "date": "2008-09-18",
      "structure": "Bgm17",
      "version": "1.2.163"
    },
    "youtube": "cypwlFD2TE4"
  },
  {
    "description": "Mu Lung Dojo Third Tier",
    "filename": "MureungSchool3",
    "mark": "MuruengRaid",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Mu Lung Raid 3",
      "year": "2008"
    },
    "source": {
      "client": "KMST",
      "date": "2008-09-18",
      "structure": "Bgm17",
      "version": "1.2.163"
    },
    "youtube": "9SKZBsjUdAg"
  },
  {
    "description": "Mu Lung Dojo Final Tier",
    "filename": "MureungSchool4",
    "mark": "MuruengRaid",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Mu Lung Raid 4",
      "year": "2008"
    },
    "source": {
      "client": "KMST",
      "date": "2008-09-18",
      "structure": "Bgm17",
      "version": "1.2.163"
    },
    "youtube": "44UN_MwwAEg"
  },
  {
    "description": "Kerning City: The Secret Garden",
    "filename": "secretFlower",
    "mark": "SecretFlower",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Secret Flower",
      "year": "2010"
    },
    "source": {
      "client": "KMST",
      "date": "2010-02-23",
      "structure": "Bgm17",
      "version": "1.2.294"
    },
    "youtube": "C0xN8QcxqXk"
  }
]

=== maplestory-music/maplebgm-db/bgm/BgmMIKU.json
[
  {
    "description": "2014 Hatsune Miku collaboration",
    "filename": "DAYBREAK",
    "mark": "1004287",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "Mafumafu feat. Hatsune Miku",
      "title": "DAYBREAK",
      "year": "2012"
    },
    "source": {
      "client": "JMS",
      "date": "2014-08-26",
      "structure": "BgmMIKU",
      "version": "3.31"
    },
    "youtube": "jwCWnyuAJFY"
  },
  {
    "description": "2014 Hatsune Miku collaboration",
    "filename": "Monokuro",
    "mark": "1004287",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "Mafumafu feat. Hatsune Miku",
      "title": "Monokuro to Yuusha no Idenshi",
      "year": "2014"
    },
    "source": {
      "client": "JMS",
      "date": "2014-08-26",
      "structure": "BgmMIKU",
      "version": "3.31"
    },
    "youtube": "JF1Nn5fWMLs"
  },
  {
    "description": "2014 Hatsune Miku collaboration",
    "filename": "next",
    "mark": "1004287",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "Satsuki ga Tenkomori feat. Hatsune Miku",
      "title": "Next Nest",
      "year": "2014"
    },
    "source": {
      "client": "JMS",
      "date": "2014-08-26",
      "structure": "BgmMIKU",
      "version": "3.31"
    },
    "youtube": "STGuvHe5NGs"
  },
  {
    "description": "2014 Hatsune Miku collaboration",
    "filename": "Sprechchor",
    "mark": "1004287",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "Satsuki ga Tenkomori feat. Hatsune Miku",
      "title": "Online Game Addicts Sprechchor",
      "year": "2010"
    },
    "source": {
      "client": "JMS",
      "date": "2014-08-26",
      "structure": "BgmMIKU",
      "version": "3.31"
    },
    "youtube": "HxquE6d_a3k"
  }
]

=== maplestory-music/maplebgm-db/bgm/BgmMH.json
[
  {
    "decoration": {
      "minorTrack": true
    },
    "description": "Mo Xuan's Unleashed Energy skill",
    "filename": "5thHyunsanpaUnleashedEnergy",
    "mark": "Hajin",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Unleashed Energy",
      "year": "2021"
    },
    "source": {
      "client": "CMST",
      "date": "2021-02-02",
      "structure": "BgmMH",
      "version": "1.67"
    },
    "youtube": "EQaK1VqKktE"
  },
  {
    "description": "Mo Xuan storyline",
    "filename": "Fate",
    "mark": "Hajin",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Fate",
      "year": "2021"
    },
    "source": {
      "client": "CMST",
      "date": "2021-02-02",
      "structure": "BgmMH",
      "version": "1.67"
    },
    "youtube": "z-ZtDeDsCpA"
  },
  {
    "description": "Mo Xuan storyline",
    "filename": "GodOfWar",
    "mark": "Hajin",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "God of War",
      "year": "2021"
    },
    "source": {
      "client": "CMST",
      "date": "2021-02-02",
      "structure": "BgmMH",
      "version": "1.67"
    },
    "youtube": "DbaFuwqTO1s"
  },
  {
    "description": "Jianghu: Hejin",
    "filename": "Hajin",
    "mark": "Hajin",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Hejin",
      "year": "2021"
    },
    "source": {
      "client": "CMST",
      "date": "2021-02-02",
      "structure": "BgmMH",
      "version": "1.67"
    },
    "youtube": "DuO0_fZkHCI"
  },
  {
    "description": "Jianghu: Xuan Mountain",
    "filename": "Hyunsan",
    "mark": "Hajin",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Xuan Mountain",
      "year": "2021"
    },
    "source": {
      "client": "CMST",
      "date": "2021-02-02",
      "structure": "BgmMH",
      "version": "1.67"
    },
    "youtube": "5cbxigyRMaY"
  },
  {
    "description": "Jianghu: Xuan Mountain School",
    "filename": "Hyunsanpa",
    "mark": "Hajin",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Xuan Mountain School",
      "year": "2021"
    },
    "source": {
      "client": "CMST",
      "date": "2021-02-02",
      "structure": "BgmMH",
      "version": "1.67"
    },
    "youtube": "6ugjjd7HaD4"
  },
  {
    "description": "Mo Xuan storyline",
    "filename": "Indomitable",
    "mark": "Hajin",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Indomitable",
      "year": "2021"
    },
    "source": {
      "client": "CMST",
      "date": "2021-02-02",
      "structure": "BgmMH",
      "version": "1.67"
    },
    "youtube": "TA3zWgdk-qk"
  },
  {
    "description": "Jianghu: Valley of Flames",
    "filename": "Threat",
    "mark": "Hajin",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Threat",
      "year": "2021"
    },
    "source": {
      "client": "CMST",
      "date": "2021-02-02",
      "structure": "BgmMH",
      "version": "1.67"
    },
    "youtube": "hS-QrEDtxuM"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm42.json
[
  {
    "description": "FriendStory Rock & Roll theme song",
    "filename": "Catch Your Dreams! full",
    "mark": "spinOff1",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Catch Your Dreams!",
      "year": "2015"
    },
    "source": {
      "client": "KMS",
      "date": "2015-03-12",
      "structure": "Bgm42",
      "version": "1.2.231"
    },
    "youtube": "4mVj4qHNLso"
  },
  {
    "description": "FriendStory Rock & Roll theme song (Japanese)",
    "filename": "Catch Your Dreams! full ~Japanese ver.~",
    "mark": "spinOff1",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Catch Your Dreams! ~Japanese ver.~",
      "year": "2015"
    },
    "source": {
      "client": "JMS",
      "date": "2015-07-29",
      "structure": "Bgm42",
      "version": "3.42"
    },
    "youtube": "ZJJvowmQ7uQ"
  },
  {
    "description": "FriendStory Rock & Roll - Chapter 6 cleared",
    "filename": "Catch Your Dreams! vocaless",
    "mark": "spinOff1",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Catch Your Dreams! ~instrumental~",
      "year": "2015"
    },
    "source": {
      "client": "KMS",
      "date": "2015-03-12",
      "structure": "Bgm42",
      "version": "1.2.231"
    },
    "youtube": "IkSVdHl2WOs"
  },
  {
    "description": "FriendStory Rock & Roll - Damien's first performance",
    "filename": "Demon's eye",
    "mark": "spinOff1",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Demon's Eye",
      "year": "2015"
    },
    "source": {
      "client": "KMS",
      "date": "2015-03-12",
      "structure": "Bgm42",
      "version": "1.2.231"
    },
    "youtube": "m7-KSFVZJzk"
  },
  {
    "description": "FriendStory Rock & Roll - Damien's concert performance",
    "filename": "Demon's eye2",
    "mark": "spinOff1",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Demon's Eye 2",
      "year": "2015"
    },
    "source": {
      "client": "KMS",
      "date": "2015-03-12",
      "structure": "Bgm42",
      "version": "1.2.231"
    },
    "youtube": "RaXC3bWEYFc"
  },
  {
    "description": "FriendStory Rock & Roll - guitar minigame against Damien",
    "filename": "TheBeast",
    "mark": "spinOff1",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The Beast",
      "year": "2015"
    },
    "source": {
      "client": "KMS",
      "date": "2015-03-12",
      "structure": "Bgm42",
      "version": "1.2.231"
    },
    "youtube": "317XVLPaHnY"
  },
  {
    "description": "FriendStory Rock & Roll - battle against Damien's Rock Zombies",
    "filename": "TheBeast2",
    "mark": "spinOff1",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The Beast 2",
      "year": "2015"
    },
    "source": {
      "client": "KMS",
      "date": "2015-03-12",
      "structure": "Bgm42",
      "version": "1.2.231"
    },
    "youtube": "axRaC6qDdLk"
  }
]

=== maplestory-music/maplebgm-db/bgm/BgmLYNN.json
[
  {
    "description": "Lynn storyline",
    "filename": "DeerMyDear",
    "mark": "ForestofEternity",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Deer My Dear",
      "year": "2024"
    },
    "source": {
      "client": "TMS",
      "date": "2024-02-21",
      "structure": "BgmLYNN",
      "version": "2.59"
    },
    "youtube": "1IjkMl4uvow"
  },
  {
    "description": "Lynn storyline",
    "filename": "EmptyWishes",
    "mark": "ForestofEternity",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Empty Wishes",
      "year": "2024"
    },
    "source": {
      "client": "TMS",
      "date": "2024-02-21",
      "structure": "BgmLYNN",
      "version": "2.59"
    },
    "youtube": "V0K-Iqk10w8"
  },
  {
    "description": "Forest of Eternity field",
    "filename": "IntoTheWoods",
    "mark": "ForestofEternity",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Into the Woods",
      "year": "2024"
    },
    "source": {
      "client": "TMS",
      "date": "2024-02-21",
      "structure": "BgmLYNN",
      "version": "2.59"
    },
    "youtube": "ZYOHMiayA7k"
  },
  {
    "description": "Forest of Eternity: Forest Entrance Cabin",
    "filename": "MyLittleCottage",
    "mark": "ForestofEternity",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "My Little Cottage",
      "year": "2024"
    },
    "source": {
      "client": "TMS",
      "date": "2024-02-21",
      "structure": "BgmLYNN",
      "version": "2.59"
    },
    "youtube": "eZiLN1NBahU"
  },
  {
    "description": "Forest of Eternity: Fountain of Reincarnation",
    "filename": "OurStoryGoesOn",
    "mark": "ForestofEternity",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Our Story Goes On",
      "year": "2024"
    },
    "source": {
      "client": "TMS",
      "date": "2024-02-21",
      "structure": "BgmLYNN",
      "version": "2.59"
    },
    "youtube": "ky0dsOW2tZY"
  },
  {
    "description": "Forest of Eternity: Sea Cliff",
    "filename": "SomewhereBeyondTheCliff",
    "mark": "ForestofEternity",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Somewhere Beyond the Cliff",
      "year": "2024"
    },
    "source": {
      "client": "TMS",
      "date": "2024-02-21",
      "structure": "BgmLYNN",
      "version": "2.59"
    },
    "youtube": "oebLavw3F4M"
  },
  {
    "description": "Forest of Eternity field",
    "filename": "WhispersOfTheTrees",
    "mark": "ForestofEternity",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Whispers of the Trees",
      "year": "2024"
    },
    "source": {
      "client": "TMS",
      "date": "2024-02-21",
      "structure": "BgmLYNN",
      "version": "2.59"
    },
    "youtube": "VuawsyejZVc"
  }
]
