=== maplestory-music/maplebgm-db/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MapleStory music database",
  "description": "Definitive MapleStory music database",
  "type": "array",
  "items": {
    "title": "MapleStory music",
    "type": "object",
    "properties": {
      "decoration": {
        "type": "object",
        "properties": {
          "minorTrack": {
            "description": "Track is a segment of another song",
            "type": "boolean"
          }
        }
      },
      "description": {
        "description": "Description of the song's usage",
        "type": "string"
      },
      "filename": {
        "type": "string"
      },
      "mark": {
        "description": "Map icon associated with the song",
        "type": "string"
      },
      "metadata": {
        "type": "object",
        "properties": {
          "albumArtist": {
            "type": "string"
          },
          "artist": {
            "type": "string"
          },
          "subtitle": {
            "description": "Song title from data",
            "type": "string"
          },
          "title": {
            "description": "Official song title",
            "type": "string"
          },
          "year": {
            "type": "string"
          }
        },
        "required": ["albumArtist", "artist", "title", "year"]
      },
      "source": {
        "type": "object",
        "properties": {
          "client": {
            "description": "Client of origin",
            "type": "string"
          },
          "date": {
            "description": "Date of release",
            "type": "string"
          },
          "structure": {
            "description": "Folder structure",
            "type": "string"
          },
          "version": {
            "description": "Version of origin",
            "type": "string"
          }
        },
        "required": ["structure"]
      },
      "youtube": {
        "description": "YouTube video identifier",
        "type": "string"
      }
    },
    "required": [
      "description",
      "filename",
      "mark",
      "metadata",
      "source",
      "youtube"
    ]
  }
}

=== maplestory-music/maplebgm-db/bgm/Bgm14.json
[
  {
    "description": "Ariant",
    "filename": "Ariant",
    "mark": "Ariant",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Ariant",
      "year": "2007"
    },
    "source": {
      "client": "KMST",
      "date": "2007-04-06",
      "structure": "Bgm14",
      "version": "1.2.80"
    },
    "youtube": "w1RgDSoOajw"
  },
  {
    "description": "Hot Desert (Old Version)",
    "filename": "Burningroad",
    "mark": "Ariant",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Burning Road",
      "year": "2007"
    },
    "source": {
      "client": "KMST",
      "date": "2007-04-06",
      "structure": "Bgm14",
      "version": "1.2.80"
    },
    "youtube": "dPK41O2-odk"
  },
  {
    "description": "Leafre: Cave of Life",
    "filename": "CaveOfHontale",
    "mark": "Leafre",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Cave of Horntail",
      "year": "2006"
    },
    "source": {
      "client": "KMS",
      "date": "2006-09-27",
      "structure": "Bgm14",
      "version": "1.2.32"
    },
    "youtube": "Lo59n_tMGSM"
  },
  {
    "description": "Leafre: Dragon Forest",
    "filename": "DragonLoad",
    "mark": "Leafre",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Dragon Load",
      "year": "2006"
    },
    "source": {
      "client": "KMS",
      "date": "2006-08-24",
      "structure": "Bgm14",
      "version": "1.2.31"
    },
    "youtube": "z3jhg8KffPI"
  },
  {
    "description": "Leafre: Dragon Canyon",
    "filename": "DragonNest",
    "mark": "Leafre",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Dragon's Nest",
      "year": "2006"
    },
    "source": {
      "client": "KMS",
      "date": "2006-09-27",
      "structure": "Bgm14",
      "version": "1.2.32"
    },
    "youtube": "Dsis2wyHQD0"
  },
  {
    "description": "Dragon Rider Party Quest",
    "filename": "DragonRider",
    "mark": "Dragonrider",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Dragon Rider",
      "year": "2009"
    },
    "source": {
      "client": "KMST",
      "date": "2009-12-21",
      "structure": "Bgm14",
      "version": "1.2.275"
    },
    "youtube": "s6zoD2gnYrA"
  },
  {
    "description": "Horntail boss theme",
    "filename": "HonTale",
    "mark": "Hontale",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Horntail",
      "year": "2006"
    },
    "source": {
      "client": "KMS",
      "date": "2006-09-27",
      "structure": "Bgm14",
      "version": "1.2.32"
    },
    "youtube": "WnLrTMmnyBc"
  },
  {
    "description": "Ariant field",
    "filename": "HotDesert",
    "mark": "Ariant",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Hot Desert",
      "year": "2007"
    },
    "source": {
      "client": "KMST",
      "date": "2007-04-13",
      "structure": "Bgm14",
      "version": "1.2.81"
    },
    "youtube": "q9swmo6309U"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm50.json
[
  {
    "description": "Limina: Near the End",
    "filename": "BlackFury",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Black Fury",
      "year": "2018"
    },
    "source": {
      "client": "KMST",
      "date": "2018-08-02",
      "structure": "Bgm50",
      "version": "1.2.072"
    },
    "youtube": "nXXepZt8Z3g"
  },
  {
    "description": "Black Mage boss theme (Phase 4)",
    "filename": "LostSpace",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Lost Space",
      "year": "2018"
    },
    "source": {
      "client": "KMST",
      "date": "2018-08-02",
      "structure": "Bgm50",
      "version": "1.2.072"
    },
    "youtube": "8XP6WdWNaCg"
  },
  {
    "description": "Black Mage battle - ending scene",
    "filename": "NewBeginningNotTheEnd",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "New Beginning, Not the End",
      "year": "2018"
    },
    "source": {
      "client": "KMS",
      "date": "2018-08-09",
      "structure": "Bgm50",
      "version": "1.2.303"
    },
    "youtube": "rBKa0sL4vfQ"
  },
  {
    "description": "Limina: Guard Captain Darknell boss theme",
    "filename": "SubterminalPoint",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Subterminal Point",
      "year": "2018"
    },
    "source": {
      "client": "KMST",
      "date": "2018-08-02",
      "structure": "Bgm50",
      "version": "1.2.072"
    },
    "youtube": "b1fOmkiX7Pg"
  },
  {
    "description": "Limina",
    "filename": "TearsOfTheWorld",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Tears of the World",
      "year": "2018"
    },
    "source": {
      "client": "KMST",
      "date": "2018-08-02",
      "structure": "Bgm50",
      "version": "1.2.072"
    },
    "youtube": "x9RBWQiDTkQ"
  },
  {
    "description": "Black Mage boss theme (Phase 1)",
    "filename": "TempleOfDarkness",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Temple of Darkness",
      "year": "2018"
    },
    "source": {
      "client": "KMST",
      "date": "2018-08-02",
      "structure": "Bgm50",
      "version": "1.2.072"
    },
    "youtube": "uJU2L5oVGrg"
  },
  {
    "description": "Limina: Where the World Ends",
    "filename": "TheWorld'sEnd",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "The World's End",
      "year": "2018"
    },
    "source": {
      "client": "KMST",
      "date": "2018-08-02",
      "structure": "Bgm50",
      "version": "1.2.072"
    },
    "youtube": "yQhYvQBmkro"
  },
  {
    "description": "Black Mage boss theme (Phase 2)",
    "filename": "ThroneOfDarkness",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Throne of Darkness",
      "year": "2018"
    },
    "source": {
      "client": "KMST",
      "date": "2018-08-02",
      "structure": "Bgm50",
      "version": "1.2.072"
    },
    "youtube": "KT5nP_ell8Y"
  },
  {
    "description": "Black Mage boss theme (Phase 3)",
    "filename": "WorldHorizon",
    "mark": "Limen",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "World Horizon",
      "year": "2018"
    },
    "source": {
      "client": "KMST",
      "date": "2018-08-02",
      "structure": "Bgm50",
      "version": "1.2.072"
    },
    "youtube": "NX0_FISZhcA"
  }
]

=== maplestory-music/maplebgm-db/bgm/PL_CaptainNomad.json
[
  {
    "description": "Captain Vaga missions",
    "filename": "Battle",
    "mark": "PL_CaptainVaga",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Unforgettable Gun",
      "titleAlt": "Battle",
      "year": "2018"
    },
    "source": {
      "client": "CMST",
      "date": "2018-04-27",
      "structure": "PL_CaptainNomad",
      "version": "1.37"
    },
    "youtube": "5faEeE3Z_fU"
  },
  {
    "description": "Captain Vaga finale",
    "filename": "CaptainVaga",
    "mark": "PL_CaptainVaga",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Escape",
      "titleAlt": "Captain Vaga",
      "year": "2018"
    },
    "source": {
      "client": "CMST",
      "date": "2018-04-27",
      "structure": "PL_CaptainNomad",
      "version": "1.37"
    },
    "youtube": "EYXHWkl_hnw"
  },
  {
    "description": "Captain Vaga intro",
    "filename": "IntotheStars",
    "mark": "PL_CaptainVaga",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Tomorrow",
      "titleAlt": "Into the Stars",
      "year": "2018"
    },
    "source": {
      "client": "CMST",
      "date": "2018-04-27",
      "structure": "PL_CaptainNomad",
      "version": "1.37"
    },
    "youtube": "3OM9ZKFWD3s"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm27.json
[
  {
    "description": "Pantheon: Angelic Buster's Room",
    "filename": "AngelsRoom",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Angel's Room",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-08-10",
      "structure": "Bgm27",
      "version": "1.2.445"
    },
    "youtube": "EC56KZErScE"
  },
  {
    "description": "Pantheon: Suspicious Hideout, Heretic Temple",
    "filename": "BaseOfBetrayers",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Base of Betrayers",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-18",
      "structure": "Bgm27",
      "version": "1.2.439"
    },
    "youtube": "TeFx8yrpzHc"
  },
  {
    "description": "Pantheon border area",
    "filename": "BorderArea",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Border Area",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-18",
      "structure": "Bgm27",
      "version": "1.2.439"
    },
    "youtube": "cxqCXm9_LsI"
  },
  {
    "description": "Pantheon: Great Temple",
    "filename": "GreatTemple",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Great Temple",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-18",
      "structure": "Bgm27",
      "version": "1.2.439"
    },
    "youtube": "CZTQdmJAEQI"
  },
  {
    "description": "Pantheon Sanctum",
    "filename": "NovaSanctum",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Nova Sanctum",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-18",
      "structure": "Bgm27",
      "version": "1.2.439"
    },
    "youtube": "NNh-dYY3MpM"
  },
  {
    "description": "Pantheon",
    "filename": "Pantheon",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Pantheon",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-18",
      "structure": "Bgm27",
      "version": "1.2.439"
    },
    "youtube": "ZYeUnqsCnxg"
  },
  {
    "description": "Pantheon field",
    "filename": "PantheonField",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Pantheon Field",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-18",
      "structure": "Bgm27",
      "version": "1.2.439"
    },
    "youtube": "Koxm5dEtkS8"
  },
  {
    "description": "Kaiser tutorial",
    "filename": "StepOfKaiser",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Step of Kaiser",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-18",
      "structure": "Bgm27",
      "version": "1.2.439"
    },
    "youtube": "r05cGa1Jms0"
  },
  {
    "description": "Kaiser tutorial",
    "filename": "TrappedKaiser",
    "mark": "Pantheon",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Trapped Kaiser",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-18",
      "structure": "Bgm27",
      "version": "1.2.439"
    },
    "youtube": "TNcUGCElU40"
  }
]

=== maplestory-music/maplebgm-db/bgm/GL_Sia.json
[
  {
    "description": "Oort: Star Garden",
    "filename": "FalterMindBecameAStarlight",
    "mark": "GL_Oort",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Falter Mind Became a Starlight",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-06-11",
      "structure": "GL_Sia",
      "version": "2.60"
    },
    "youtube": "6JL2Y8e1d4Q"
  },
  {
    "description": "Oort: Star Forest",
    "filename": "FateForest",
    "mark": "GL_Oort",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Fate Forest",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-06-11",
      "structure": "GL_Sia",
      "version": "2.60"
    },
    "youtube": "AsJ2ehBy1es"
  },
  {
    "description": "Perion: Astronomy Lab",
    "filename": "FriendBecameAStar",
    "mark": "GL_OortLab",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Friend Became a Star",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-06-11",
      "structure": "GL_Sia",
      "version": "2.60"
    },
    "youtube": "GDkTZp0ucZE"
  },
  {
    "description": "Oort: Sea of Darkened Stars",
    "filename": "GraveyardOfTheStar",
    "mark": "GL_Oort",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Graveyard of the Star",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-06-11",
      "structure": "GL_Sia",
      "version": "2.60"
    },
    "youtube": "3kRn4NC32bE"
  },
  {
    "description": "Oort: Twinkling Valley",
    "filename": "LittleStarsHappyDelusion",
    "mark": "GL_Oort",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Little Star's Happy Delusion",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-06-11",
      "structure": "GL_Sia",
      "version": "2.60"
    },
    "youtube": "mYvsr2eIW-k"
  },
  {
    "description": "Oort Lobby",
    "filename": "StarGuardian",
    "mark": "GL_Oort",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "The Guardian of the Stars",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-06-11",
      "structure": "GL_Sia",
      "version": "2.60"
    },
    "youtube": "fCUPkw1Dsco"
  },
  {
    "description": "Oort",
    "filename": "ThelullabyOort",
    "mark": "GL_Oort",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "The Lullaby Oort",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-06-11",
      "structure": "GL_Sia",
      "version": "2.60"
    },
    "youtube": "najOnl1mXW0"
  }
]

=== maplestory-music/maplebgm-db/bgm/PL_WinterFrenzy.json
[
  {
    "description": "2016 Icy Onslaught event",
    "filename": "WinterFrenzy_Boss_All",
    "mark": "Event",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Frenzy Winter (Alternate)",
      "titleAlt": "Winter Frenzy Boss (All)",
      "year": "2016"
    },
    "source": {
      "client": "GMS",
      "date": "2016-11-30",
      "structure": "PL_WinterFrenzy",
      "version": "1.78"
    },
    "youtube": "dwlGJS1b08g"
  },
  {
    "description": "2016 Icy Onslaught event",
    "filename": "WinterFrenzy_Boss_Bgm",
    "mark": "Event",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Frenzy Winter",
      "titleAlt": "Winter Frenzy Boss (BGM)",
      "year": "2016"
    },
    "source": {
      "client": "GMS",
      "date": "2016-11-30",
      "structure": "PL_WinterFrenzy",
      "version": "1.78"
    },
    "youtube": "w9FJhoIyLqs"
  }
]

=== maplestory-music/maplebgm-db/bgm/PL_Sound.json
[
  {
    "description": "2025 GlobalMS MapleCon LA 'Build a Monster!' in-game event",
    "filename": "Twenteena_Exit",
    "mark": "1006520",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Twenteena -Exit-",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-12-17",
      "structure": "PL_Sound",
      "version": "2.65"
    },
    "youtube": "UsM2PVz2meU"
  },
  {
    "description": "2025 GlobalMS MapleCon LA 'Build a Monster!' in-game event",
    "filename": "Twenteena_Main",
    "mark": "1006520",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Twenteena -Main-",
      "year": "2025"
    },
    "source": {
      "client": "GMS",
      "date": "2025-12-17",
      "structure": "PL_Sound",
      "version": "2.65"
    },
    "youtube": "8sJEoJSNAuY"
  }
]

=== maplestory-music/maplebgm-db/bgm/PL_Beautyroid.json
[
  {
    "description": "Mechanical Hearts: Aspire - Hidden Hallway",
    "filename": "Beautyroid3_HiddenHallway",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Hidden Hallway",
      "year": "2020"
    },
    "source": {
      "client": "GMS",
      "date": "2020-01-29",
      "structure": "PL_Beautyroid",
      "version": "2.11"
    },
    "youtube": "aentFD_-8uo"
  },
  {
    "description": "Mechanical Hearts Season 3 ending",
    "filename": "Beautyroid3_MoreHumanThanHuman",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "More Human Than Human",
      "year": "2020"
    },
    "source": {
      "client": "GMS",
      "date": "2020-01-29",
      "structure": "PL_Beautyroid",
      "version": "2.11"
    },
    "youtube": "VrAPwZk0CFI"
  },
  {
    "description": "Mechanical Hearts: Aspire - Scion's Lair",
    "filename": "Beautyroid3_ScionsLair",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Scion's Lair",
      "year": "2020"
    },
    "source": {
      "client": "GMS",
      "date": "2020-01-29",
      "structure": "PL_Beautyroid",
      "version": "2.11"
    },
    "youtube": "t6sLGm66uWY"
  },
  {
    "description": "Mechanical Hearts - Scion's Invitation chair effect",
    "filename": "Beautyroid3_UnseenPrison",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Unseen Prison",
      "year": "2020"
    },
    "source": {
      "client": "GMS",
      "date": "2020-01-29",
      "structure": "PL_Beautyroid",
      "version": "2.11"
    },
    "youtube": "_t9zVOFNVlY"
  },
  {
    "description": "Mechanical Hearts: Aspire Industries factory",
    "filename": "Beautyroid_Factory",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Beautyroid Factory",
      "year": "2017"
    },
    "source": {
      "client": "CMST",
      "date": "2017-04-12",
      "structure": "PL_Beautyroid",
      "version": "1.25"
    },
    "youtube": "IqfKfW0KQ0g"
  },
  {
    "description": "Mechanical Hearts: Aspire Industries forest hideout",
    "filename": "Beautyroid_Forrest",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Beautyroid Forest",
      "year": "2017"
    },
    "source": {
      "client": "CMST",
      "date": "2017-04-12",
      "structure": "PL_Beautyroid",
      "version": "1.25"
    },
    "youtube": "wnSwoYrY70Q"
  },
  {
    "description": "Mechanical Hearts: Aspire Industries lab",
    "filename": "Beautyroid_Lab",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Beautyroid Lab",
      "year": "2017"
    },
    "source": {
      "client": "CMST",
      "date": "2017-04-12",
      "structure": "PL_Beautyroid",
      "version": "1.25"
    },
    "youtube": "aHR0xM6CVQ0"
  },
  {
    "description": "Mechanical Hearts: Aspire Industries lobby",
    "filename": "Beautyroid_Lobby",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Beautyroid Lobby",
      "year": "2017"
    },
    "source": {
      "client": "CMST",
      "date": "2017-04-12",
      "structure": "PL_Beautyroid",
      "version": "1.25"
    },
    "youtube": "-aT2UF3yW1I"
  },
  {
    "description": "Mechanical Hearts: Episode 2",
    "filename": "PeacefulDays",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Peaceful Life",
      "titleAlt": "Peaceful Days",
      "year": "2017"
    },
    "source": {
      "client": "CMST",
      "date": "2017-11-16",
      "structure": "PL_Beautyroid",
      "version": "1.32"
    },
    "youtube": "_Gt9PQYmhIg"
  },
  {
    "description": "Mechanical Hearts: Episode 2 ending",
    "filename": "Primrose",
    "mark": "PL_Beautyroid",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Primrose",
      "year": "2017"
    },
    "source": {
      "client": "CMST",
      "date": "2017-11-16",
      "structure": "PL_Beautyroid",
      "version": "1.32"
    },
    "youtube": "gw7gbAh0hZA"
  }
]
