=== maplestory-music/maplebgm-db/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MapleStory music database",
  "description": "Definitive MapleStory music database",
  "type": "array",
  "items": {
    "title": "MapleStory music",
    "type": "object",
    "properties": {
      "decoration": {
        "type": "object",
        "properties": {
          "minorTrack": {
            "description": "Track is a segment of another song",
            "type": "boolean"
          }
        }
      },
      "description": {
        "description": "Description of the song's usage",
        "type": "string"
      },
      "filename": {
        "type": "string"
      },
      "mark": {
        "description": "Map icon associated with the song",
        "type": "string"
      },
      "metadata": {
        "type": "object",
        "properties": {
          "albumArtist": {
            "type": "string"
          },
          "artist": {
            "type": "string"
          },
          "subtitle": {
            "description": "Song title from data",
            "type": "string"
          },
          "title": {
            "description": "Official song title",
            "type": "string"
          },
          "year": {
            "type": "string"
          }
        },
        "required": ["albumArtist", "artist", "title", "year"]
      },
      "source": {
        "type": "object",
        "properties": {
          "client": {
            "description": "Client of origin",
            "type": "string"
          },
          "date": {
            "description": "Date of release",
            "type": "string"
          },
          "structure": {
            "description": "Folder structure",
            "type": "string"
          },
          "version": {
            "description": "Version of origin",
            "type": "string"
          }
        },
        "required": ["structure"]
      },
      "youtube": {
        "description": "YouTube video identifier",
        "type": "string"
      }
    },
    "required": [
      "description",
      "filename",
      "mark",
      "metadata",
      "source",
      "youtube"
    ]
  }
}

=== maplestory-music/maplebgm-db/bgm/Bgm26.json
[
  {
    "description": "Luminous tutorial",
    "filename": "BurningWoods",
    "mark": "Ellinia",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Burning Woods",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-03",
      "structure": "Bgm26",
      "version": "1.2.437"
    },
    "youtube": "fPVOc5uau1M"
  },
  {
    "description": "Luminous tutorial, Black Mage encounter",
    "filename": "DarkMage",
    "mark": "TimeTemple",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Dark Mage",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-03",
      "structure": "Bgm26",
      "version": "1.2.437"
    },
    "youtube": "PLGbYlBbw2E"
  },
  {
    "description": "Luminous storyline",
    "filename": "DarkWoods",
    "mark": "Ellinia",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Dark Woods",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-03",
      "structure": "Bgm26",
      "version": "1.2.437"
    },
    "youtube": "ekBYanDkybM"
  },
  {
    "description": "Luminous tutorial, Black Mage's Temple",
    "filename": "FinalFight (Tempest)",
    "mark": "TimeTemple",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Final Fight",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-03",
      "structure": "Bgm26",
      "version": "1.2.437"
    },
    "youtube": "R5dUCq4vnvk"
  },
  {
    "description": "Luminous tutorial",
    "filename": "Flood",
    "mark": "Ellinia",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Flood",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-03",
      "structure": "Bgm26",
      "version": "1.2.437"
    },
    "youtube": "1cipH9qIEow"
  },
  {
    "description": "Luminous tutorial",
    "filename": "PeacefulWoods",
    "mark": "Ellinia",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Peaceful Woods",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-03",
      "structure": "Bgm26",
      "version": "1.2.437"
    },
    "youtube": "6BqN9qhPoGQ"
  },
  {
    "description": "Luminous storyline",
    "filename": "Serenity",
    "mark": "Ellinia",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Serenity",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-03",
      "structure": "Bgm26",
      "version": "1.2.437"
    },
    "youtube": "bDKPdN8rUko"
  },
  {
    "description": "Luminous tutorial",
    "filename": "SpeakInTheVoid",
    "mark": "TimeTemple",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Speak in the Void",
      "year": "2012"
    },
    "source": {
      "client": "KMST",
      "date": "2012-07-03",
      "structure": "Bgm26",
      "version": "1.2.437"
    },
    "youtube": "0-ANvxookZ0"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm37.json
[
  {
    "description": "Tower of Oz boss theme",
    "filename": "AmusingStoryInTheFairyTale",
    "mark": "aquarisTower",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Amusing Story in the Fairytale",
      "year": "2014"
    },
    "source": {
      "client": "KMST",
      "date": "2014-01-08",
      "structure": "Bgm37",
      "version": "1.2.495"
    },
    "youtube": "ZnS7JgfB8DI"
  },
  {
    "description": "Tower of Oz - 26F, 27F, 34F",
    "filename": "HazardFromCave",
    "mark": "aquarisTower",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Hazard from the Cave",
      "year": "2014"
    },
    "source": {
      "client": "KMST",
      "date": "2014-01-08",
      "structure": "Bgm37",
      "version": "1.2.495"
    },
    "youtube": "STDN57rytW8"
  },
  {
    "description": "Tower of Oz: 11-14F, 33F, 48F",
    "filename": "JungleInTheSea",
    "mark": "aquarisTower",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Jungle in the Sea",
      "year": "2014"
    },
    "source": {
      "client": "KMST",
      "date": "2014-01-08",
      "structure": "Bgm37",
      "version": "1.2.495"
    },
    "youtube": "_5qyICio6MQ"
  },
  {
    "description": "Tower of Oz: 47F, 49-50F, Dorothy boss theme",
    "filename": "StrangeSortOfStory",
    "mark": "aquarisTower",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Strange Sort of Story",
      "year": "2014"
    },
    "source": {
      "client": "KMST",
      "date": "2014-01-08",
      "structure": "Bgm37",
      "version": "1.2.495"
    },
    "youtube": "AZU1lB4WrlU"
  },
  {
    "description": "Tower of Oz shelter (5F, 15F, 25F, 35F, 45F)",
    "filename": "TheBottomOfTheSea",
    "mark": "aquarisTower",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "The Bottom of the Sea",
      "year": "2014"
    },
    "source": {
      "client": "KMST",
      "date": "2014-01-08",
      "structure": "Bgm37",
      "version": "1.2.495"
    },
    "youtube": "XPnJrBwv0zM"
  },
  {
    "description": "Tower of Oz lobby",
    "filename": "VentureIntoTheUnkown",
    "mark": "aquarisTower",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Venture Into the Unknown",
      "year": "2014"
    },
    "source": {
      "client": "KMST",
      "date": "2014-01-08",
      "structure": "Bgm37",
      "version": "1.2.495"
    },
    "youtube": "qr9eW2y2EJM"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm06.json
[
  {
    "description": "Orbis Tower",
    "filename": "ComeWithMe",
    "mark": "Orbis",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Come With Me",
      "year": "2004"
    },
    "source": {
      "client": "KMS",
      "date": "2004-04-22",
      "structure": "Bgm06",
      "version": "1.60"
    },
    "youtube": "sNCwJu5Buz0"
  },
  {
    "description": "Ludibrium",
    "filename": "FantasticThinking",
    "mark": "Ludibrium",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Fantastic Thinking",
      "year": "2004"
    },
    "source": {
      "client": "KMS",
      "date": "2004-12-20",
      "structure": "Bgm06",
      "version": "1.81"
    },
    "youtube": "49AZqVhXVeU"
  },
  {
    "description": "Zakum boss theme",
    "filename": "FinalFight",
    "mark": "Zakum",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Final Fight",
      "year": "2004"
    },
    "source": {
      "client": "KMS",
      "date": "2004-10-25",
      "structure": "Bgm06",
      "version": "1.76"
    },
    "youtube": "rEtDrkAYs68"
  },
  {
    "description": "Ship to Ludibrium, Continental travel (Ossyria)",
    "filename": "FlyingInABlueDream",
    "mark": "Ludibrium",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "CODASOUND",
      "title": "Flying in a Blue Dream",
      "year": "2004"
    },
    "source": {
      "client": "KMS",
      "date": "2004-12-20",
      "structure": "Bgm06",
      "version": "1.81"
    },
    "youtube": "UywGQsCoj8c"
  },
  {
    "description": "El Nath: Zakum's Altar",
    "filename": "WelcomeToTheHell",
    "mark": "Zakum",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Welcome to Hell",
      "year": "2004"
    },
    "source": {
      "client": "KMS",
      "date": "2004-10-25",
      "structure": "Bgm06",
      "version": "1.76"
    },
    "youtube": "3EJFx4emHyk"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm54.json
[
  {
    "description": "Yum Yum Island: Fungus Forest",
    "filename": "FungusForest",
    "mark": "YumYum",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Fungus Forest",
      "year": "2020"
    },
    "source": {
      "client": "KMST",
      "date": "2020-02-06",
      "structure": "Bgm54",
      "version": "1.2.098"
    },
    "youtube": "h3EKe2b5kYI"
  },
  {
    "description": "Yum Yum Island: Fungus Forest",
    "filename": "FungusForestB",
    "mark": "YumYum",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Fungus Forest -Ver. B-",
      "year": "2020"
    },
    "source": {
      "client": "KMST",
      "date": "2020-02-06",
      "structure": "Bgm54",
      "version": "1.2.098"
    },
    "youtube": "DrCzk_r0tUE"
  },
  {
    "description": "Yum Yum Island: Illiyard Field",
    "filename": "IlliyardMoor",
    "mark": "YumYum",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ESTIMATE",
      "title": "Illiyard Moor",
      "year": "2020"
    },
    "source": {
      "client": "KMST",
      "date": "2020-02-06",
      "structure": "Bgm54",
      "version": "1.2.098"
    },
    "youtube": "GkJHzTUQdiU"
  },
  {
    "description": "Reverse City cutscene",
    "filename": "MemoryOfSunset",
    "mark": "Reverse_City",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Memory of Sunset",
      "year": "2019"
    },
    "source": {
      "client": "KMST",
      "date": "2019-12-12",
      "structure": "Bgm54",
      "version": "1.2.095"
    },
    "youtube": "eTneN70g90M"
  },
  {
    "description": "Yum Yum Island: Yum Yum Village",
    "filename": "MushbudForest",
    "mark": "YumYum",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "Initium SoundLab",
      "title": "Mushbud Forest",
      "year": "2020"
    },
    "source": {
      "client": "KMST",
      "date": "2020-02-06",
      "structure": "Bgm54",
      "version": "1.2.098"
    },
    "youtube": "TD0abMaS0Sk"
  },
  {
    "description": "Reverse City underground",
    "filename": "ReverseCity",
    "mark": "Reverse_City",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Reverse City",
      "year": "2019"
    },
    "source": {
      "client": "KMST",
      "date": "2019-12-12",
      "structure": "Bgm54",
      "version": "1.2.095"
    },
    "youtube": "Z5sInHxNTRg"
  },
  {
    "description": "Reverse City: M Tower",
    "filename": "ReverseCity2",
    "mark": "Reverse_City",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Reverse City 2",
      "year": "2019"
    },
    "source": {
      "client": "KMST",
      "date": "2019-12-12",
      "structure": "Bgm54",
      "version": "1.2.095"
    },
    "youtube": "CSAsQCLnB7U"
  },
  {
    "description": "Reverse City: M Tower boss theme",
    "filename": "T-bomb",
    "mark": "Reverse_City",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "T-bomb",
      "year": "2019"
    },
    "source": {
      "client": "KMST",
      "date": "2019-12-12",
      "structure": "Bgm54",
      "version": "1.2.095"
    },
    "youtube": "b6k9HwW5EE0"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm61.json
[
  {
    "description": "Nightmare Wonderland",
    "filename": "Ashes of spring",
    "mark": "nightmareParadise",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Ashes of Spring",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-09-11",
      "structure": "Bgm61",
      "version": "1.2.193"
    },
    "youtube": "hcCWV0lqQgs"
  },
  {
    "description": "First Adversary - Phase 1",
    "filename": "Courage Unbreakable",
    "mark": "firstAdversary",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Courage Unbreakable",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-08-14",
      "structure": "Bgm61",
      "version": "1.2.192"
    },
    "youtube": "IWXmRItfYsM"
  },
  {
    "description": "Nightmare Wonderland",
    "filename": "Feast of evil spirits",
    "mark": "nightmareParadise",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Feast of Evil Spirits",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-09-11",
      "structure": "Bgm61",
      "version": "1.2.193"
    },
    "youtube": "-PLcCJV6s0g"
  },
  {
    "description": "First Adversary - Entrance",
    "filename": "Gate of Proof",
    "mark": "firstAdversary",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Gate of Proof",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-08-14",
      "structure": "Bgm61",
      "version": "1.2.192"
    },
    "youtube": "_5r-2JTJowM"
  },
  {
    "description": "Vallora mountain zone",
    "filename": "If you follow the mountain path",
    "mark": "Vallora",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "If You Follow the Mountain Path",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-06-07",
      "structure": "Bgm61",
      "version": "1.2.188"
    },
    "youtube": "hLG-h805Wcc"
  },
  {
    "description": "Vallora",
    "filename": "Port city of Balora",
    "mark": "Vallora",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Port City of Vallora",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-06-07",
      "structure": "Bgm61",
      "version": "1.2.188"
    },
    "youtube": "lyp4mlh3abI"
  },
  {
    "description": "Nightmare Wonderland storyline",
    "filename": "Rebirth of life",
    "mark": "nightmareParadise",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Rebirth of Life",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-09-11",
      "structure": "Bgm61",
      "version": "1.2.193"
    },
    "youtube": "HlnALPLQut8"
  },
  {
    "description": "Vallora: Serpent's Lake",
    "filename": "Serpent's Lake",
    "mark": "Vallora",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Serpent's Lake",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-06-07",
      "structure": "Bgm61",
      "version": "1.2.188"
    },
    "youtube": "ipl9FrvjEPU"
  },
  {
    "description": "First Adversary - Reward Map",
    "filename": "Succession Bloom",
    "mark": "firstAdversary",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Succession Bloom",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-08-14",
      "structure": "Bgm61",
      "version": "1.2.192"
    },
    "youtube": "pevUhp_jxnU"
  },
  {
    "description": "Nightmare Wonderland",
    "filename": "The downfall",
    "mark": "nightmareParadise",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "The Downfall",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-09-11",
      "structure": "Bgm61",
      "version": "1.2.193"
    },
    "youtube": "rP5UgQ71d14"
  },
  {
    "description": "First Adversary - Phase 3",
    "filename": "Voice of Verdict",
    "mark": "firstAdversary",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Voice of Verdict",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-08-14",
      "structure": "Bgm61",
      "version": "1.2.192"
    },
    "youtube": "3xpCpPHwsQ0"
  },
  {
    "description": "Len storyline",
    "filename": "When the wind blows",
    "mark": "Vallora",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "When the Wind Blows",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-06-07",
      "structure": "Bgm61",
      "version": "1.2.188"
    },
    "youtube": "ArFkvhHvLsE"
  },
  {
    "description": "Vallora beach zone",
    "filename": "Wind flowing in the harbor",
    "mark": "Vallora",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Wind Flowing in the Harbor",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-06-07",
      "structure": "Bgm61",
      "version": "1.2.188"
    },
    "youtube": "mKhyvIKVW18"
  },
  {
    "description": "First Adversary - Phase 2",
    "filename": "Wisdom Beyond Aspirations",
    "mark": "firstAdversary",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Wisdom Beyond Aspirations",
      "year": "2025"
    },
    "source": {
      "client": "KMST",
      "date": "2025-08-14",
      "structure": "Bgm61",
      "version": "1.2.192"
    },
    "youtube": "OeKYxq_TX_Y"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm58.json
[
  {
    "description": "Odium: Occupied Alley",
    "filename": "Alley on the Other Side",
    "mark": "odium",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Alley on the Other Side",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-08-18",
      "structure": "Bgm58",
      "version": "1.2.145"
    },
    "youtube": "Dhoag52TV_w"
  },
  {
    "description": "Explorer storyline",
    "filename": "Endless Curse",
    "mark": "MushroomVillage",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Endless Curse",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-01-18",
      "structure": "Bgm58",
      "version": "1.2.136"
    },
    "youtube": "UwuyxDRPkmI"
  },
  {
    "description": "Odium storyline",
    "filename": "Four Perils Astray",
    "mark": "odium",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Four Perils Astray",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-08-18",
      "structure": "Bgm58",
      "version": "1.2.145"
    },
    "youtube": "Orjgsq8R-CU"
  },
  {
    "description": "Odium: Laboratory Behind Locked Doors",
    "filename": "Irreversible Abomination",
    "mark": "odium",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Irreversible Abomination",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-08-18",
      "structure": "Bgm58",
      "version": "1.2.145"
    },
    "youtube": "XCg3agTZ7t8"
  },
  {
    "description": "Explorer storyline - character progression",
    "filename": "Just Another Maple Leaf",
    "mark": "MushroomVillage",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Just Another Maple Leaf",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-01-18",
      "structure": "Bgm58",
      "version": "1.2.136"
    },
    "youtube": "7NN_k0auDWQ"
  },
  {
    "description": "Cygnus Knights - Mihile storyline",
    "filename": "Knight of Light",
    "mark": "Ereb",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Knight of Light",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-06-23",
      "structure": "Bgm58",
      "version": "1.2.143"
    },
    "youtube": "_e9YXlxlCqA"
  },
  {
    "description": "Ereve: Nobleman's Estate",
    "filename": "Noblesse nostalgia",
    "mark": "Ereb",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Noblesse Nostalgia",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-06-23",
      "structure": "Bgm58",
      "version": "1.2.143"
    },
    "youtube": "u2TQ4DFqSSw"
  },
  {
    "description": "Cygnus Knights storyline - God's Shelter",
    "filename": "Resting place of God",
    "mark": "Ereb",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Resting Place of God",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-06-23",
      "structure": "Bgm58",
      "version": "1.2.143"
    },
    "youtube": "QstADc5R4GI"
  },
  {
    "description": "Odium: Sunny Laboratory",
    "filename": "Sunshine blurring the Unknown",
    "mark": "odium",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Sunshine Blurring the Unknown",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-08-18",
      "structure": "Bgm58",
      "version": "1.2.145"
    },
    "youtube": "N2dyV-2UeK8"
  },
  {
    "description": "Maple Island",
    "filename": "The Beginnig of The Adventure",
    "mark": "MushroomVillage",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "The Beginning of the Adventure",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-01-18",
      "structure": "Bgm58",
      "version": "1.2.136"
    },
    "youtube": "-bSIQVSEdgM"
  },
  {
    "description": "Odium",
    "filename": "The Lost City among the Clouds",
    "mark": "odium",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "The Lost City Among the Clouds",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-08-18",
      "structure": "Bgm58",
      "version": "1.2.145"
    },
    "youtube": "34Tb70dLN3Q"
  },
  {
    "description": "Grand Athenaeum: Maple Chronicles",
    "filename": "The other side of the dimension",
    "mark": "Library",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "The Other Side of the Dimension",
      "year": "2022"
    },
    "source": {
      "client": "KMST",
      "date": "2022-10-20",
      "structure": "Bgm58",
      "version": "1.2.147"
    },
    "youtube": "1dUnek_TBRk"
  },
  {
    "description": "Monster Park Extreme",
    "filename": "Warning! Unknown Area",
    "mark": "Carnival",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Warning! Unknown Area",
      "year": "2022"
    },
    "source": {
      "client": "KMS",
      "date": "2022-07-28",
      "structure": "Bgm58",
      "version": "1.2.367"
    },
    "youtube": "Nkh_YN1PRP4"
  }
]

=== maplestory-music/maplebgm-db/bgm/Bgm36.json
[
  {
    "description": "Shade tutorial",
    "filename": "decision",
    "mark": "TimeTemple",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Decision",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-12-23",
      "structure": "Bgm36",
      "version": "1.2.494"
    },
    "youtube": "fajX5WR07mw"
  },
  {
    "description": "Night Walker's Dominion skill",
    "filename": "Dominion",
    "mark": "Ereb",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Dominion",
      "year": "2014"
    },
    "source": {
      "client": "KMST",
      "date": "2014-04-10",
      "structure": "Bgm36",
      "version": "1.2.501"
    },
    "youtube": "Or2OSeGbPV0"
  },
  {
    "description": "Fox Point Village",
    "filename": "foxvillage",
    "mark": "foxvillage",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Fox Village",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-12-09",
      "structure": "Bgm36",
      "version": "1.2.493"
    },
    "youtube": "lorm88ckSuM"
  },
  {
    "description": "11th anniversary festival",
    "filename": "HappyTimeLong",
    "mark": "MinigameStation",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Happy Time",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-12-09",
      "structure": "Bgm36",
      "version": "1.2.493"
    },
    "youtube": "wzBIoro1jIs"
  },
  {
    "description": "Elite Boss bonus stage",
    "filename": "HappyTimeShort",
    "mark": "FreeMarket",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Happy Time (Short Version)",
      "year": "2013"
    },
    "source": {
      "client": "KMS",
      "date": "2013-12-19",
      "structure": "Bgm36",
      "version": "1.2.206"
    },
    "youtube": "RknHVs7vDlw"
  },
  {
    "description": "Shade's Reincarnated Fox God skill",
    "filename": "LightOfTheFoxGoddess",
    "mark": "foxvillage",
    "metadata": {
      "albumArtist": "NECORD",
      "artist": "ASTERIA",
      "title": "Forgotten Radiance",
      "year": "2024"
    },
    "source": {
      "client": "KMST",
      "date": "2024-06-08",
      "structure": "Bgm36",
      "version": "1.2.174"
    },
    "youtube": "SfnK7L_rHaU"
  },
  {
    "description": "Elite Boss theme",
    "filename": "RoyalGuard",
    "mark": "FreeMarket",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Royal Guard",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-12-09",
      "structure": "Bgm36",
      "version": "1.2.493"
    },
    "youtube": "ui4YM2l2i4o"
  },
  {
    "description": "Rainy Fox Point Village",
    "filename": "sadfoxvillage",
    "mark": "foxvillage",
    "metadata": {
      "albumArtist": "Wizet",
      "artist": "StudioEIM",
      "title": "Sad Fox Village",
      "year": "2013"
    },
    "source": {
      "client": "KMST",
      "date": "2013-12-23",
      "structure": "Bgm36",
      "version": "1.2.494"
    },
    "youtube": "4oNXYkRrf-g"
  }
]
